In [1]:
#assignment [numpy]
import numpy as np
x=np.array([1,2,3,4,])
y=np.array([5.5,6.5,7.5,8.5])
np.add(x,y)

array([ 6.5,  8.5, 10.5, 12.5])

In [5]:
import numpy as np
x=np.array([1,2,3,4,])
y=np.array([5.5,6.5,7.5,8.5])
np.subtract(x,y)

array([-4.5, -4.5, -4.5, -4.5])

In [7]:
import numpy as np
x=np.array([1,2,3,4,])
y=np.array([5.5,6.5,7.5,8.5])
np.multiply(x,y)

array([ 5.5, 13. , 22.5, 34. ])

In [9]:
import numpy as np
x=np.array([1,2,3,4,])
y=np.array([5.5,6.5,7.5,8.5])
np.divide(x,y)

array([0.18181818, 0.30769231, 0.4       , 0.47058824])

In [12]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [14]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.max(x,axis=0)

array([3, 4])

In [1]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.max(x,axis=1)

array([2, 4])

In [2]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.min(x,axis=1)

array([1, 3])

In [19]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.median(x,axis=0)

array([2., 3.])

In [21]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.median(x,axis=1)

array([1.5, 3.5])

In [23]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.std(x,axis=0)

array([1., 1.])

In [25]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.std(x,axis=1)

array([0.5, 0.5])

In [27]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.mean(x,axis=0)

array([2., 3.])

In [29]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.mean(x,axis=1)

array([1.5, 3.5])

In [31]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [2]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.power(x,4)


array([[  1,  16],
       [ 81, 256]], dtype=int32)

In [4]:
#assignment [pandas]
import pandas as pd
students=[{'sony':[6+7+8+9+8],
           'raji':[9+6+9+10+8],
           'soha':[4+7+8+8+7],
           'tony':[6+7+8+9+6],
           'sakshi':[7+8+9+8+7]}]
students_marks=pd.DataFrame(students,index=['total'])
x=students_marks.max(axis=1)
print(x)

total    [42]
dtype: object


In [6]:
#assignment
data=[{'Year':1990,'Name':'alice','Department':'HR','Age':25,'Salary':50000},
      {'Year':1990,'Name':'bob','Department':'RD','Age':30,'Salary':48000},
      {'Year':1990,'Name':'charlie','Department':'Admin','Age':45,'Salary':55000},
      {'Year':1991,'Name':'alice','Department':'HR','Age':26,'Salary':52000},
      {'Year':1991,'Name':'bob','Department':'RD','Age':31,'Salary':50000},
      {'Year':1991,'Name':'charlie','Department':'Admin','Age':46,'Salary':60000},
      {'Year':1992,'Name':'alice','Department':'Admin','Age':27,'Salary':60000},
      {'Year':1992,'Name':'bob','Department':'RD','Age':32,'Salary':52000},
      {'Year':1992,'Name':'charlie','Department':'Admin','Age':28,'Salary':62000}]
data_info=pd.DataFrame(data,index=[0,1,2,3,4,5,6,7,8])
data_info

Age Department     Name  Salary  Year
0   25         HR    alice   50000  1990
1   30         RD      bob   48000  1990
2   45      Admin  charlie   55000  1990
3   26         HR    alice   52000  1991
4   31         RD      bob   50000  1991
5   46      Admin  charlie   60000  1991
6   27      Admin    alice   60000  1992
7   32         RD      bob   52000  1992
8   28      Admin  charlie   62000  1992

In [8]:
data_info.groupby(['Year'])['Salary'].sum()

Year
1990    153000
1991    162000
1992    174000
Name: Salary, dtype: int64

In [10]:
data_info.groupby(['Name'])['Salary'].sum()

Name
alice      162000
bob        150000
charlie    177000
Name: Salary, dtype: int64

In [11]:
data_info.groupby(['Year','Department'])['Salary'].sum()

Year  Department
1990  Admin          55000
      HR             50000
      RD             48000
1991  Admin          60000
      HR             52000
      RD             50000
1992  Admin         122000
      RD             52000
Name: Salary, dtype: int64